version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '10:00'
    timezone: Japan
  open-pull-requests-limit: 1
  labels:
  - "dependencies"
  commit-message:
    prefix: deps

- package-ecosystem: pip
  directory: "docs/Tutorial-PyTorch"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Japan
  open-pull-requests-limit: 1
  labels:
  - "dependencies"
  commit-message:
    prefix: deps

- package-ecosystem: pip
  directory: "docs/Tutorial-TensorFlow"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Japan
  open-pull-requests-limit: 1
  labels:
  - "dependencies"
  commit-message:
    prefix: deps
