version: 2
updates:
- package-ecosystem: pip
  directory:
  - "docs/tutorials/deep_learning"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Japan
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 1
  labels:
  - dependencies
  commit-message:
    prefix: deps
