version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '10:00'
    timezone: Japan
  labels:
  - "CI/CD"
  commit-message:
    prefix: ci
  reviewers:
    - "peaceiris"

- package-ecosystem: pip
  directory: "docs/dev"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Japan
  labels:
  - "dependencies"
  commit-message:
    prefix: deps
  reviewers:
    - "peaceiris"

# - package-ecosystem: pip
#   directory: "docs/Tutorial-Bing-Image-Search"
#   schedule:
#     interval: daily
#     time: '10:00'
#     timezone: Japan
#   labels:
#   - "dependencies"
#   commit-message:
#     prefix: deps

# - package-ecosystem: pip
#   directory: "docs/Tutorial-PyTorch"
#   schedule:
#     interval: daily
#     time: '10:00'
#     timezone: Japan
#   labels:
#   - "dependencies"
#   commit-message:
#     prefix: deps

# - package-ecosystem: pip
#   directory: "docs/Tutorial-TensorFlow"
#   schedule:
#     interval: daily
#     time: '10:00'
#     timezone: Japan
#   labels:
#   - "dependencies"
#   commit-message:
#     prefix: deps
