version: '3'

services:
  mkdocs:
    # https://github.com/peaceiris/mkdocs-material-boilerplate
    image: ghcr.io/peaceiris/mkdocs-material:v3.3.8
    container_name: siaizu_documentation_mkdocs
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/root
    stdin_open: true
    tty: true
    command:
      - "mkdocs"
      - "serve"
      - "--dev-addr=0.0.0.0:8888"
