version: '3'

services:
  dev:
    container_name: deep_learning_tutorial_pytorch
    build: .
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/src
    stdin_open: true
    tty: true
    command:
      - bash
