version: '3.2'

services:
  dev:
    image: 'docker.pkg.github.com/si-aizu/documentation/pytorch:v1.5.1'
    build:
      context: .
      cache_from:
        - 'docker.pkg.github.com/si-aizu/documentation/pytorch:v1.5.1'
    container_name: siaizu_documentation_pytorch
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/src
    stdin_open: true
    tty: true
    command:
      - bash
