version: '3'

services:
  dev:
    image: 'docker.pkg.github.com/si-aizu/documentation/pytorch:v1.11.0'
    build:
      context: .
      cache_from:
        - 'docker.pkg.github.com/si-aizu/documentation/pytorch:v1.11.0'
    container_name: siaizu_documentation_pytorch
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 8000:8000
    volumes:
      - .:/src
    stdin_open: true
    tty: true
    command:
      - bash
