version: '3.2'

services:
  dev:
    image: 'docker.pkg.github.com/si-aizu/documentation/pytorch:latest'
    build:
      context: .
      cache_from:
        - 'docker.pkg.github.com/si-aizu/documentation/pytorch:latest'
    container_name: deep_learning_tutorial_pytorch
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/src
    stdin_open: true
    tty: true
    command:
      - bash
