version: '3.2'

services:
  dev:
    image: 'docker.pkg.github.com/si-aizu/documentation/tensorflow-models:v2.3.0-gpu'
    build:
      context: .
      cache_from:
        - 'docker.pkg.github.com/si-aizu/documentation/tensorflow-models:v2.3.0-gpu'
    container_name: siaizu_documentation_tensorflow_models
    volumes:
      - ${PWD}:/src/models/research/object_detection/siaizu
    stdin_open: true
    tty: true
    command:
      - bash
