version: '3'

services:
  dev:
    build: .
    image: google_images_download
    container_name: google_images_download
    volumes:
      - ${PWD}:/src
    stdin_open: true
    tty: true
    command:
      - bash
