name: CI Tutorial-TensorFlow

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci-Tutorial-TensorFlow.yml'
      - 'docs/Tutorial-TensorFlow/**'
      - '!**.md'
  pull_request:
    paths:
      - '.github/workflows/ci-Tutorial-TensorFlow.yml'
      - 'docs/Tutorial-TensorFlow/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs/Tutorial-TensorFlow
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Login to Packages
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login 'docker.pkg.github.com' -u 'peaceiris' --password-stdin
      - run: make pull
        if: github.event_name == 'pull_request'
      - run: make build
      - run: make push
        if: github.ref == 'refs/heads/master'
