name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**.py'

jobs:
  main:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2.3.1
      - run: make build
      - run: make cifmt
      - run: make lint
