name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'docs/Tutorial-PyTorch/**'
      - '!**.md'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'docs/Tutorial-PyTorch/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs/Tutorial-PyTorch
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose run --rm dev python3 -m pip check
