name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'docs/Tutorial-PyTorch/**'
      - 'docs/Tutorial-TensorFlow/**'
      - '!**.md'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'docs/Tutorial-PyTorch/**'
      - 'docs/Tutorial-TensorFlow/**'
      - '!**.md'

jobs:
  test-Tutorial-PyTorch:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs/Tutorial-PyTorch
    steps:
      - uses: actions/checkout@v2.3.1
      - run: docker-compose build
      - run: docker-compose run --rm dev python3 -m pip check

  test-Tutorial-TensorFlow:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs/Tutorial-TensorFlow
    steps:
      - uses: actions/checkout@v2.3.1
      - run: make build
