name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs/tutorials/deep_learning
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose run --rm dev python3 -m pip check
