name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - '**.py'
      - 'docs/dev/**'
      - 'docs/.dockerignore'
      - 'docs/.flake8'
      - 'docs/Dockerfile'
      - 'docs/Makefile'
      - 'docs/docker-compose.yml'
      - 'docs/pyproject.toml'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**.py'
      - 'docs/dev/**'
      - 'docs/.dockerignore'
      - 'docs/.flake8'
      - 'docs/Dockerfile'
      - 'docs/Makefile'
      - 'docs/docker-compose.yml'
      - 'docs/pyproject.toml'

jobs:
  main:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2.3.1
      - run: make build
      - run: make cifmt
      - run: make ciisort
      - run: make lint
