name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose run --rm mkdocs build
