name: github pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'docker-compose.yml'
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'docker-compose.yml'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - run: docker-compose pull --quiet
      - run: docker-compose run --rm mkdocs mkdocs build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ github.token }}
          publish_dir: ./site
