name: github pages

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'docker-compose.yml'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose run --rm mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./site
