name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/hadolint.yml'
      - '**/.hadolint.yaml'
      - '**/Dockerfile'
  pull_request:
    paths:
      - '.github/workflows/hadolint.yml'
      - '**/.hadolint.yaml'
      - '**/Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    container:
      image: 'hadolint/hadolint:v2.9.1-alpine'
    steps:
      - uses: actions/checkout@v3
      - name: Lint PyTorch
        working-directory: 'docs/Tutorial-PyTorch'
        run: hadolint ./Dockerfile
      - name: Lint TensorFlow
        working-directory: 'docs/Tutorial-TensorFlow'
        run: hadolint ./Dockerfile
      - name: Lint TensorFlow Models
        working-directory: 'docs/Tutorial-TensorFlow-Models'
        run: hadolint ./Dockerfile
      - name: Lint Darknet YOLO
        working-directory: 'docs/Tutorial-YOLO-Darknet'
        run: hadolint ./Dockerfile
      - name: Lint Bing Image Search
        working-directory: 'docs/Tutorial-Bing-Image-Search'
        run: hadolint ./Dockerfile
