name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/hadolint.yml'
      - '**/.hadolint.yaml'
      - '**/Dockerfile'
  pull_request:
    paths:
      - '.github/workflows/hadolint.yml'
      - '**/.hadolint.yaml'
      - '**/Dockerfile'

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    container:
      image: 'hadolint/hadolint:v2.9.1-alpine'
    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfile
        run: |
          for d in $(find . -type f -name "Dockerfile" -exec dirname {} \;); do
            (cd ${d} && hadolint Dockerfile)
          done
