name: hadolint

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/hadolint.yml'
      - '**/.hadolint.yaml'
      - '**/Dockerfile'
  pull_request:
    paths:
      - '.github/workflows/hadolint.yml'
      - '**/.hadolint.yaml'
      - '**/Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-18.04
    container:
      image: 'hadolint/hadolint:v1.18.0-alpine'
    steps:
      - uses: actions/checkout@v2
      - name: Lint PyTorch
        working-directory: 'docs/Tutorial-PyTorch'
        run: hadolint ./Dockerfile
      - name: Lint TensorFlow
        working-directory: 'docs/Tutorial-TensorFlow'
        run: hadolint ./Dockerfile
      - name: Lint 
        working-directory: 'docs/Tutorial-YOLO-Darknet'
        run: hadolint ./Dockerfile
